In [4]:
import torch

# Atributos de un Tensor 

In [5]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0905, 0.0071, 0.9472, 0.8345],
        [0.4212, 0.4849, 0.3151, 0.6391],
        [0.1695, 0.9189, 0.5325, 0.2927]])

In [6]:
print('Data type: ',some_tensor.dtype)
print('Tensor Shape: ',some_tensor.shape)
print('Tensor Device: ',some_tensor.device)

Data type:  torch.float32
Tensor Shape:  torch.Size([3, 4])
Tensor Device:  cpu


# Manipulacion

In [7]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [8]:
tensor *10

tensor([10, 20, 30])

In [9]:
torch.mul(tensor,5)

tensor([ 5, 10, 15])

In [10]:
torch.add(tensor,2)

tensor([3, 4, 5])

In [11]:
# Matrix Multiplciacion
torch.matmul(tensor,tensor)

tensor(14)

## Multiplicacion de Matrices

Problemas con la dimensiones de las matrices
1. Los **valores internos** al momento de multiplicar debe coincidir:
    * (3,2) @ (3,2) no funcionará
    * (2,3) @ (3,2) funcionará
    * (3,2) @ (2,3) funcionará
2. El resultado de la multiplicacion de las matrices tiene el tamaño de los **valores externos** de cada matriz:
    * (2,3) @ (3,2) -> (2,2)
    * (3,2) @ (2,3) -> (3,3)
  
matrixmultiplication.xyz
   

In [ ]:
torch.

In [12]:
torch.matmul(torch.rand(3,10),torch.rand(10,3))

tensor([[2.6643, 1.6013, 2.5866],
        [2.4156, 1.9370, 2.2431],
        [1.5407, 1.6808, 2.3172]])

In [13]:
tensorA = torch.tensor([[1,2],
                        [3,4],
                       [5,6]])
tensorB = torch.tensor([[7,8],
                      [9,10],
                      [11,12]])

In [14]:
torch.mm(tensorA,tensorB.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Tensor Agregation

In [15]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [16]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [17]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [21]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [22]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [23]:
x.argmax()

tensor(9)

Tipos de Errores:
- Dimensionalidad
- Data type
- Device

## Reshaping, stacking, squeezing and unqueezing
* Reshape - redefina un tensor a una forma definida
* Stack - concatena una secuencia de tensores sobre una nueva dimension
* Squeeze - remueve todas aquellas dimensiones con dimension tamaño 1
* Unsqueeze - añade una dimension de valor 1 al tensor
* Permute - reodena las dimensiones de un tensor

In [25]:
import torch

In [63]:
# add extra dimension
x = torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [64]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [35]:
x = torch.arange(1,15)
x,x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 torch.Size([14]))

In [39]:
x_reshaped = x.reshape(2,7)
x_reshaped,x_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14]]),
 torch.Size([2, 7]))

In [50]:
# Stack
torch.stack([x_reshaped,x_reshaped], axis=2)

tensor([[[ 1,  1],
         [ 2,  2],
         [ 3,  3],
         [ 4,  4],
         [ 5,  5],
         [ 6,  6],
         [ 7,  7]],

        [[ 8,  8],
         [ 9,  9],
         [10, 10],
         [11, 11],
         [12, 12],
         [13, 13],
         [14, 14]]])

In [53]:
torch.vstack([x_reshaped,x_reshaped])-

tensor([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]])

In [76]:
xx = torch.hstack([x_reshaped,x_reshaped])
xx

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
# Squeeze
x_reshaped.squeeze()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
torch.unsqueeze(xx,2),torch.unsqueeze(xx,2).shape

(tensor([[[1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9]]]),
 torch.Size([1, 18, 1]))

In [85]:
# Permutacion
x_img = torch.rand((224,224,3))
x_img.shape

torch.Size([224, 224, 3])

In [87]:
x_img_perm = torch.permute(x_img,(2,0,1))
x_img_perm.shape

torch.Size([3, 224, 224])

## Array to Tensor

In [10]:
import torch 
import numpy as np

array = np.arange(1.0,8)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [11]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float64)

In [14]:
numpy_tensor = tensor.numpy()
numpy_tensor, numpy_tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))

## Reproducibilidad

In [19]:
# Para una linea

seed = 123
torch.manual_seed(seed)
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)

print(tensor_A)
print(tensor_B)
## no sol iguales

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])
tensor([[0.1366, 0.1025, 0.1841],
        [0.7264, 0.3153, 0.6871]])


In [21]:
seed = 123
torch.manual_seed(seed)
torch.rand(2,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [24]:
# Para el proyecto
seed = 321

gen = torch.Generator()
gen = gen.manual_seed(0)
torch.rand(2,3,generator=gen)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])

In [25]:
torch.rand(2,3,generator=gen)

tensor([[0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017]])

 # GPU

In [28]:
!nvidia-smi

Tue Jan  9 09:45:39 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.36                 Driver Version: 546.33       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070        On  | 00000000:01:00.0  On |                  N/A |
|  0%   35C    P5              19W / 200W |    843MiB / 12282MiB |      9%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [30]:
# chech GPU access
import torch

torch.cuda.is_available()

True

In [34]:
# Device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## Tensors en GPU

In [36]:
tensor = torch.rand(2,3)
tensor, tensor.device

(tensor([[0.2745, 0.6584, 0.2775],
         [0.8573, 0.8993, 0.0390]]),
 device(type='cpu'))

In [40]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)